/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#fff8f1",
        "surface-dim": "#e0d9d1",
        "surface-bright": "#fff8f1",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#faf2ea",
        "surface-container": "#f4ede5",
        "surface-container-high": "#eee7df",
        "surface-container-highest": "#e8e1d9",
        "on-surface": "#1e1b17",
        "on-surface-variant": "#3e4947",
        "inverse-surface": "#33302b",
        "inverse-on-surface": "#f7f0e7",
        outline: "#6e7977",
        "outline-variant": "#bdc9c6",
        "surface-tint": "#006b60",
        primary: "#005f55",
        "on-primary": "#ffffff",
        "primary-container": "#0d7a6e",
        "on-primary-container": "#abfff0",
        "inverse-primary": "#7dd6c8",
        secondary: "#835500",
        "on-secondary": "#ffffff",
        "secondary-container": "#feae2c",
        "on-secondary-container": "#6b4500",
        tertiary: "#aa0a17",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ce2b2c",
        "on-tertiary-container": "#ffeae8",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#99f3e4",
        "primary-fixed-dim": "#7dd6c8",
        "on-primary-fixed": "#00201c",
        "on-primary-fixed-variant": "#005048",
        "secondary-fixed": "#ffddb4",
        "secondary-fixed-dim": "#ffb955",
        "on-secondary-fixed": "#291800",
        "on-secondary-fixed-variant": "#633f00",
        "tertiary-fixed": "#ffdad6",
        "tertiary-fixed-dim": "#ffb3ac",
        "on-tertiary-fixed": "#410003",
        "on-tertiary-fixed-variant": "#930010",
        background: "#fff8f1",
        "on-background": "#1e1b17",
        "surface-variant": "#e8e1d9",
        "chat-bg": "#ECE5DD",
        "user-bubble": "#DCF8C6",
        warning: "#F5A623",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        base: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "container-margin": "16px",
        "chat-gap": "4px",
      },
      fontFamily: {
        sans: ["Noto Sans", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
      },
    },
  },
  plugins: [],
};
